
get http://localhost:3000/customer/login/checklogin
###
GET http://localhost:3000/tours/3
###
POST http://localhost:3000/tour
Content-Type: application/json

{
  "cid": 4,
  "tid": 4
}
###
GET http://localhost:3000/customer/17
###
GET http://localhost:3000/customer/tours/3
###
DELETE http://localhost:3000/tour?customer=3&tour=7
###
POST http://localhost:3000/customer
Content-Type: application/json

{
  "firstname": "Ruben",
  "lastname": "Müllauer",
  "username": "OnFireFrog22",
  "password": "Heute12",
  "email": "muellauer.r19@htlwienwest.at",
  "plz": 1160,
  "street": "Lienfeldergasse",
  "city": "Vienna"

}
###
POST http://localhost:3000/customer/login
Content-Type: application/json

{
  "username": "OnFireFrog22",
  "password": "Heute12"
}
###
PATCH http://localhost:3000/customer
Content-Type: application/json

{
  "newUser": "alicej",
  "oldUser": "OnFeuerFrosch"
}